In [1]:
# Del emp from the nested list if found otherwise display message that employee doesn't exist
emps = [[1,'AAA'],[2,'BBB'],[3,'CCC']]

In [2]:
emps

[[1, 'AAA'], [2, 'BBB'], [3, 'CCC']]

In [5]:
#Prompt the user to enter the emp-id, check if the employee exists or not! 
# if exists display the index of the emp
eid = int(input("Enter employee-id you want to remove/delete :: "))
for i in range(len(emps)):
    if emps[i][0] == eid:
        print("Employee Found at index :: ",i)
    

Enter employee-id you want to remove/delete :: 3
Employee Found at index ::  2


In [8]:
#If found delete the employee
eid = int(input("Enter employee-id you want to remove/delete :: "))
if(len(emps)>0):
    for i in range(len(emps)):
        if emps[i][0] == eid:
            print("Employee Found at index :: ",i)
            emps.pop(i)
            print("Employee info delete successfully! ")
            break;
else:
    print("No employee exists to process the data!")

Enter employee-id you want to remove/delete :: 1
Employee Found at index ::  0
Employee info delete successfully! 


In [9]:
emps

[[3, 'CCC']]

In [11]:
#If found delete the employee
eid = int(input("Enter employee-id you want to remove/delete :: "))
if(len(emps)>0):
    for i in range(len(emps)):
        if emps[i][0] == eid:
            print("Employee Found at index :: ",i)
            emps.pop(i)
            print("Employee info delete successfully! ")
            break;
else:
    print("No employee exists to process the data!")

Enter employee-id you want to remove/delete :: 1


In [12]:
emps

[[3, 'CCC']]

In [13]:
#If found delete the employee
eid = int(input("Enter employee-id you want to remove/delete :: "))
if(len(emps)>0):
    for i in range(len(emps)):
        if emps[i][0] == eid:
            print("Employee Found at index :: ",i)
            emps.pop(i)
            print("Employee info delete successfully! ")
            break;
else:
    print("No employee exists to process the data!")

Enter employee-id you want to remove/delete :: 3
Employee Found at index ::  0
Employee info delete successfully! 


In [14]:
emps

[]

In [15]:
#If found delete the employee
eid = int(input("Enter employee-id you want to remove/delete :: "))
if(len(emps)>0):
    for i in range(len(emps)):
        if emps[i][0] == eid:
            print("Employee Found at index :: ",i)
            emps.pop(i)
            print("Employee info delete successfully! ")
            break;
else:
    print("No employee exists to process the data!")

Enter employee-id you want to remove/delete :: 5
No employee exists to process the data!


In [16]:
emps = [[1,'AAA'],[2,'BBB'],[3,'CCC']]

In [17]:
emps

[[1, 'AAA'], [2, 'BBB'], [3, 'CCC']]

In [18]:
#If found delete the employee otherwise display message employee not found or doesn't exist
eid = int(input("Enter employee-id you want to remove/delete :: "))
dstat = False
if(len(emps)>0):
    for i in range(len(emps)):
        if emps[i][0] == eid:
            print("Employee Found at index :: ",i)
            emps.pop(i)
            print("Employee info delete successfully! ")
            dstat=True
            break;
    if dstat != True:
        print("Employee not found and not deleted!")
else:
    print("No employee exists to process the data!")

Enter employee-id you want to remove/delete :: 101
Employee not found and not deleted!


In [19]:
def del_Emp():
    eid = int(input("Enter employee-id you want to remove/delete :: "))
    dstat = False
    if(len(emps)>0):
        for i in range(len(emps)):
            if emps[i][0] == eid:
                print("Employee Found at index :: ",i)
                emps.pop(i)
                print("Employee info delete successfully! ")
                dstat=True
                break;
        if dstat != True:
            print("Employee not found and not deleted!")
    else:
        print("No employee exists to process the data!")

In [20]:
del_Emp()

Enter employee-id you want to remove/delete :: 101
Employee not found and not deleted!


In [21]:
emps

[[1, 'AAA'], [2, 'BBB'], [3, 'CCC']]

In [23]:
del_Emp()

Enter employee-id you want to remove/delete :: 2
Employee Found at index ::  1
Employee info delete successfully! 


In [24]:
emps

[[1, 'AAA'], [3, 'CCC']]

In [25]:
del_Emp()

Enter employee-id you want to remove/delete :: 105
Employee not found and not deleted!


In [26]:
del_Emp()

Enter employee-id you want to remove/delete :: 1
Employee Found at index ::  0
Employee info delete successfully! 


In [27]:
emps

[[3, 'CCC']]

In [28]:
del_Emp()

Enter employee-id you want to remove/delete :: 3
Employee Found at index ::  0
Employee info delete successfully! 


In [29]:
emps

[]

In [31]:
del_Emp()

Enter employee-id you want to remove/delete :: 5
No employee exists to process the data!


In [33]:
def del_Emp():
    if(len(emps)>0):
        eid = int(input("Enter employee-id you want to remove/delete :: "))
        dstat = False
        for i in range(len(emps)):
            if emps[i][0] == eid:
                print("Employee Found at index :: ",i)
                emps.pop(i)
                print("Employee info delete successfully! ")
                dstat=True
                break;
        if dstat != True:
            print("Employee not found and not deleted!")
    else:
        print("Employee List is Empty Cannot delete the data!")

In [34]:
emps = [[1,'AAA'],[2,'BBB'],[3,'CCC']]

In [35]:
del_Emp()

Enter employee-id you want to remove/delete :: 5
Employee not found and not deleted!


In [36]:
del_Emp()

Enter employee-id you want to remove/delete :: 2
Employee Found at index ::  1
Employee info delete successfully! 


In [37]:
del_Emp()

Enter employee-id you want to remove/delete :: 101
Employee not found and not deleted!


In [38]:
emps

[[1, 'AAA'], [3, 'CCC']]

In [39]:
del_Emp()

Enter employee-id you want to remove/delete :: 1
Employee Found at index ::  0
Employee info delete successfully! 


In [40]:
emps

[[3, 'CCC']]

In [41]:
del_Emp()

Enter employee-id you want to remove/delete :: 3
Employee Found at index ::  0
Employee info delete successfully! 


In [42]:
emps

[]

In [43]:
del_Emp()

Employee List is Empty Cannot delete the data!


In [44]:
import numpy as np

In [45]:
a = np.array([1,2,3,4,5])

In [46]:
for e in a:
    print(e)

1
2
3
4
5


In [47]:
a = np.array([1,'Hello',True,10,10])

In [48]:
for e in a:
    print(e)

1
Hello
True
10
10


In [49]:
print(np.__version__)

1.26.0


In [50]:
type(a)

numpy.ndarray

In [51]:
a = np.array((1,2,3,4,'Hello',True,False,1.234,100,100))

In [52]:
for e in a:
    print(e)

1
2
3
4
Hello
True
False
1.234
100
100


In [65]:
a = np.array({1,2,3,1,2,3,4,5})

In [66]:
len(a)

TypeError: len() of unsized object

In [67]:
a.size

1

In [68]:
a.shape

()

In [54]:
a

array({1, 2, 3, 4, 5}, dtype=object)

In [55]:
type(a)

numpy.ndarray

In [69]:
a = np.array({1:1,2:'b','c':'c',4:"dell",'a':'apple'})

In [70]:
a

array({1: 1, 2: 'b', 'c': 'c', 4: 'dell', 'a': 'apple'}, dtype=object)

In [58]:
type(a)

numpy.ndarray

In [59]:
for e in a:
    print(e)

TypeError: iteration over a 0-d array

In [60]:
a.size

1

In [61]:
a.shape

()

In [63]:
a.size

1

In [64]:
len(a)

TypeError: len() of unsized object

In [71]:
for item in a.items():
    print(item)

AttributeError: 'numpy.ndarray' object has no attribute 'items'

In [81]:
a = np.array(10)

In [82]:
a

array(10)

In [83]:
a.size

1

In [84]:
a.shape

()

In [85]:
a.ndim

0

In [86]:
b = np.array([1,2,3])

In [87]:
b.size

3

In [88]:
b.shape

(3,)

In [89]:
b.ndim

1

In [90]:
c = np.array([[1,2,3],[4,5,6]])

In [91]:
c.size

6

In [92]:
c.shape

(2, 3)

In [93]:
c.ndim

2

In [94]:
d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [95]:
d.size

12

In [100]:
d.shape

(2, 2, 3)

In [99]:
d.ndim

3

In [101]:
print(a)
print(b)
print(c)
print(d)

10
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [103]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
3
6
12


In [104]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [105]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


In [72]:
class Emp:
    def __init__(self,eno,ena):
        self.eno = eno
        self.ena = ena
        
    def getEno(self):
        return self.eno
    
    def getEna(self):
        return self.ena
    
    


In [73]:
e1 = Emp(1,'Aaa')

In [74]:
e1.eno

1

In [75]:
e1.ena

'Aaa'

In [78]:
emps = [Emp(101,'Aaa'),Emp(102,'Bbb'),Emp(103,'Ccc')]

In [79]:
emps

In [80]:
for e in emps:
    print(e.eno,' ',e.ena)

101   Aaa
102   Bbb
103   Ccc


In [116]:
def delEmp():
    if(len(emps)>0):
        eid = int(input("Enter employee-id whose record you want to remove :: "))
        delstat = False
        for i in range(len(emps)):
            if emps[i].getEno() == eid:
                emps.pop(i)
                delstat=True
                break
        if delstat == True :
            print("Employee deleted successfully")
        else:
            print("Employee with given Emp-id not found hence couldn't be deleted!")
    else:
        print("Employee list empty! No option to delete any Employee.")

In [112]:
delEmp()

Enter employee-id whose record you want to remove :: 104
Employee with given Emp-id not found hence couldn't be deleted!


In [113]:
delEmp()

Enter employee-id whose record you want to remove :: 101
Employee with given Emp-id not found hence couldn't be deleted!


In [115]:
for e in emps:
    print(e.getEno(),' ',e.getEna())

102   Bbb
103   Ccc


In [117]:
delEmp()

Enter employee-id whose record you want to remove :: 103
Employee deleted successfully


In [118]:
for e in emps:
    print(e.getEno(),' ',e.getEna())

102   Bbb


In [119]:
delEmp()

Enter employee-id whose record you want to remove :: 102
Employee deleted successfully


In [120]:
for e in emps:
    print(e.getEno(),' ',e.getEna())

In [121]:
delEmp()

Employee list empty! No option to delete any Employee.


In [122]:
a

array(10)

In [123]:
a[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [124]:
b

array([1, 2, 3])

In [126]:
b[0]

1

In [127]:
b[1]

2

In [128]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
c[0][0]

1

In [130]:
c[0,0]

1

In [131]:
c[1,2]

6

In [132]:
c[1][2]

6